apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://gitlab.sikalabs.com/clients-public/pss/pss-charts.git
    path: charts/pss-app
    helm:
      valueFiles:
      - $values/apps/dev/counter/redis.values.yml
  - repoURL: 'https://gitlab.sikalabs.com/clients-public/pss/pss-argocd-apps.git'
    ref: values
