apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-vault-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: counter
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://gitlab.sikalabs.com/examples/pss/pss-charts.git
    path: charts/pss-vault-auth
    helm:
      releaseName: counter
      valuesObject:
        role: read-all
