# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
# https://artifacthub.io/packages/helm/bitnami/keycloak?modal=values
replicaCount: 1
proxy: edge
image:
  repository: sikalabs/bitnami-keycloak-sikalabs-theme
  tag: 25.0.5-debian-12-r1
  pullPolicy: Always
auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin
  managementUser: manager
  managementPassword: manager
proxyAddressForwarding: true
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: sso.k8s.sikademo.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
postgresql:
  image:
    tag: 15.8.0-debian-12-r11
  auth:
    postgresPassword: pg
    password: pg
