apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account360-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: account360
  destination:
    namespace: account360
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: https://gitlab.sikalabs.com/clients-public/pss/pss-charts.git
    path: charts/pss-app
    helm:
      valueFiles:
      - '$values/backend.values.yml'
  - repoURL: 'https://gitlab.sikalabs.com/clients-public/pss/pps-account360-values.git'
    ref: values
